apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: kube-system
  labels:
    app: logstash
data:
  pipeline.conf: |-
    input {
      beats {
        port => 5044
      }
    }

    output {
      stdout { codec => rubydebug }
    }