app:
  name: ${appName}
  version: ${version}
  build: ${buildNumber}

server:
  port: 8002

management:
  server:
    port: 8003
    ssl:
      enabled: false
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  path: '/var/log/'