app:
  name: ${appName}
  version: ${version}
  build: ${buildNumber}

server:
  port: 8002

management:
  server:
    port: 8003
    ssl:
      enabled: false
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false


#logging:
#  path: '/var/log/'