spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bootitdb
    username: postgres
    password: postgres
